pipeline:
  clone:
    image: plugins/git
    recursive: true
    commands:
      - git init
      - git remote add origin https://github.com/drone-test-org/reddit-mobile.git
      - git fetch --no-tags --depth=1 origin
      - git reset --hard -q ${DRONE_COMMIT}
    when:
      event: [ push, deployment ]

  build:
    image: quay.io/reddit/reddit-nodejs:latest
    pull: true
    commands:
      - echo "true"
      - env
      # - npm install
      # - npm run lint
      # - npm run test
      # - npm run build
    when:
      event: [ push, deployment ]


  # publish:
  #   image: plugins/docker
  #   username: ${QUAY_USERNAME}
  #   password: ${QUAY_PASSWORD}
  #   email: sysops@reddit.com
  #   registry: quay.io
  #   repo: quay.io/reddit/reddit-mobile
  #   tag: ${DRONE_BRANCH}
  #   dockerfile: Dockerfile.staging
  #   when:
  #     event: [ push ]

  add-deployment:
    image: ruby
    pull: true
    commands:
      - gem install octokit
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} GITHUB_REPO=${DRONE_REPO} GIT_REF=${DRONE_COMMIT_REF} ruby github-deployment.rb
    when:
      event: [ push ]

  deploy-staging:
    image: lachlanevenson/k8s-helm:v2.4.2
    commands:
      - helm upgrade $${DRONE_BRANCH##refs/heads/} helm/reddit-mobile --install --set=deployment_name="$${DRONE_BRANCH##refs/heads/}" --set=branch_name="$${DRONE_BRANCH##refs/heads/}" --set=commit_sha="${DRONE_COMMIT}" --set=deployer_name="${DRONE_COMMIT_AUTHOR}" --set=service_name="$${DRONE_BRANCH##refs/heads/}"
    volumes:
      - /root/.kube/config:/root/.kube/config
    when:
      event: [ deployment ]
      environment: staging

  comment-deployment-success:
    image: ruby
    pull: true
    commands:
      - gem install octokit
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} GITHUB_REPO=${DRONE_REPO} DEPLOYMENT_URL=${DRONE_COMMIT_LINK} GIT_BRANCH=${DRONE_BRANCH} ruby github-comment.rb
    when:
      event: [ deployment ]
      environment: staging
