pipeline:
  build:
    image: quay.io/reddit/reddit-nodejs:latest
    pull: true
    commands:
      - echo "true"
      - env
      # - npm install
      # - npm run lint
      # - npm run test
      # - npm run build


  publish:
    image: plugins/docker
    username: ${QUAY_USERNAME}
    password: ${QUAY_PASSWORD}
    email: sysops@reddit.com
    registry: quay.io
    repo: quay.io/reddit/reddit-mobile
    tag: ${DRONE_BRANCH}
    dockerfile: Dockerfile.staging
    when:
      event: [ push, tag, deployment, pull_request ]

  add-deployment:
    image: ruby
    pull: true
    commands:
      - gem install octokit
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} GITHUB_REPO=drone-test-org/reddit-mobile GITHUB_PULL_REQUEST_NUMBER=${DRONE_PULL_REQUEST} GIT_BRANCH=${DRONE_BRANCH} GIT_REF=${DRONE_COMMIT_REF} ruby github-release.rb

  deploy-staging:
    image: lachlanevenson/k8s-helm:v2.4.2
    commands:
      - helm upgrade ${DRONE_BRANCH} helm/reddit-mobile --install --set=deployment_name="${DRONE_BRANCH}" --set=branch_name="${DRONE_BRANCH}" --set=commit_sha="${DRONE_COMMIT}" --set=deployer_name="${DRONE_COMMIT_AUTHOR}" --set=service_name="${DRONE_BRANCH}"
    volumes:
      - /root/.kube/config:/root/.kube/config
    when:
      event: deployment
      environment: staging
