pipeline:
  tester:
    image: ubuntu:latest
    pull: true
    commands:
      - ls /root
      - ls /root/.kube/
      - ls /root/.kube/config 
      - cat /root/.kube/config
      - echo '$QUAY_USERNAME'
      - echo '$QUAY_USERNAME'
    volumes:
      - /root/.kube/config:/root/.kube/config

  build:
    image: quay.io/reddit/reddit-nodejs:latest
    pull: true
    commands:
      - npm install
      - npm run lint
      - npm run test
      - npm run build
    environment:
      DOCKER_LAUNCH_DEBUG: "true"

  publish:
    image: plugins/docker 
    username: ${QUAY_USERNAME}
    password: ${QUAY_PASSWORD}
    email: sysops@reddit.com
    registry: quay.io
    repo: reddit/reddit-mobile
    tag: ${DRONE_BRANCH}
    dockerfile: Dockerfile.staging
    debug: true
