language: node_js

node_js:
    - "5"
    - "6"

script:
    - npm run build
    - npm run lint
    - npm run test

branches:
  except:
    - staging

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
